using Microsoft.Scripting.Hosting;
using System;
using System.Diagnostics;
using System.IO;
using System.Windows.Forms;

namespace Scrabble
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        private void Button_MouseClick(object sender, EventArgs e)
        {
            Button btn = (Button)sender;
            MessageBox.Show(btn.Text, "");
        }


        public string run_cmd(string cmd, string args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = @"C:\Users\Mrah\AppData\Local\Programs\Python\Python38-32\python.exe";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }

        public bool checkWord(string word)
        {
            string result = run_cmd(@"C:\Users\Mrah\PycharmProjects\WordChecker\CheckWord.py", "\"" + word + "\"");

            return String.Equals(result.ToLower().Trim(), "true");

        }

        private void Form1_Load(object sender, EventArgs e)
        {
            BoardHandler bh = new BoardHandler();
            bh.GenerateBoard(pnlBoard, Button_MouseClick);
            MessageBox.Show(checkWord("Uwu").ToString(), "");
        }
    }
}
